# frozen_string_literal: true
name 'micro-nodes'
maintainer 'Cem Gencer'
maintainer_email 'o.cem.gencer@gmail.com'
license 'Apache-2.0'
description 'Installs/Configures default config, databases and users'
version '0.1.0'
depends 'postgresql'
depends 'mariadb'
depends 'sc-mongodb'
