create table public."Contents" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title character varying null,
  content text null,
  type character varying null,
  parent_id bigint null,
  owner_id bigint null,
  content_json json null,
  parent_type character varying null,
  updated_at timestamp without time zone null,
  main_category character varying null,
  attributes json null,
  score smallint null default '-1'::smallint,
  status character varying null,
  uuid uuid null default gen_random_uuid (),
  taxonomy json null,
  constraint Contents_pkey primary key (id)
) TABLESPACE pg_default;

create table public."CrossBindings" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id smallint null,
  content_id smallint null,
  type character varying null,
  extra json null,
  score smallint null,
  constraint CrossBindings_pkey primary key (id)
) TABLESPACE pg_default;

create table public."Users" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "userName" character varying null,
  "firstName" character varying null,
  "lastName" character varying null,
  email character varying null,
  password character varying null,
  birthday date null,
  wallet character varying null,
  updated_at timestamp without time zone null,
  bgg_id character varying null,
  bga_id character varying null,
  avatar character varying null,
  uuid uuid null default gen_random_uuid (),
  social json null,
  taxonomy json null,
  constraint Users_pkey primary key (id)
) TABLESPACE pg_default;