# -*- mode: ruby -*-
# vi: set ft=ruby :
$DEF_IF = `route -n get default | grep interface | awk '{print $2}'`

BOX_IMAGE = "bento/ubuntu-16.04"
NODE_COUNT = 3
PORTS = Array({:a => "a", :b => "b"}) 
# Get Chef json
VAGRANT_JSON = JSON.parse(Pathname(__FILE__).dirname.join("vm-config.json").read)
PORTS = VAGRANT_JSON["ports"]

$userScript = <<SCRIPT
  cd /home/vagrant
  wget -qO- https://raw.github.com/creationix/nvm/master/install.sh | sh
  # This enables NVM without a logout/login
  export NVM_DIR="/home/vagrant/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
  nvm install stable
  # You can also install other stuff here
  npm install -g bower create-react-app
SCRIPT

$reverseProxy = <<-EOS
upstream backend {
	server localhost:8080;
}

server {
	listen 80 default_server;
	listen [::]:80 default_server ipv6only=on;

	server_name localhost;

	location / {
EOS

$bootScript = <<-SHELL
	systemctl stop postfix.service
	systemctl disable postfix.service
	yum update -y
	yum install -y wget vim nano net-tools initscripts gcc make tar bind-utils nc git unzip sysstat tree
SHELL

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin?("vagrant-omnibus")
	config.omnibus.chef_version = "latest"
  end

  if Vagrant.has_plugin?("vagrant-hostmanager")
	config.hostmanager.enabled = true
	config.hostmanager.manage_guest = true
	config.hostmanager.manage_host = true
	config.hostmanager.ignore_private_ip = false
	config.hostmanager.include_offline = true
	config.hostmanager.aliases = %w(
	  intranet.dev
	)
  end

  config.ssh.forward_agent = true

  config.vm.box = "dfsi/multisitebase"
  #config.vm.box_url = "file:///tmp/centos7"
  config.vm.provider :virtualbox do |vb|
    vb.name = "lin"
    vb.customize ["modifyvm",:id,"--usb","on"]
	vb.gui = false
	vb.memory = "2048"
  end

  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subsystem|
      subsystem.vm.box = BOX_IMAGE
	  subsystem.vm.name = "node_#{i}"
	  subsystem.vm.hostname = "lin"
	  subsystem.hostmanager.aliases = %w(node_#{i}.localdomain node_#{i})

	  subsystem.ssh.username = "vagrant"
	  subsystem.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key"]
	  subsystem.ssh.insert_key = false

		#node[:Production][:ApplicationLayer][:DockerTag]

	  PORTS.each do |item|
	  	$nfo = item['nfo'].nil? ? item['nfo'] : 'tcp'
	  	if item['nod'] == i || item['nod'] == '-1'
			subsystem.vm.network :forwarded_port, 
				guest: item['gst'], 
				host: item['hst'], 
				id: $nfo, 
				auto_correct: true
		end
	  end

	  subsystem.vm.synced_folder ".", "/vagrant", disabled: true
	  subsystem.vm.synced_folder "../dist/", "/var/www/html", :nfs => { :mount_options => ["dmode=777","fmode=777"] }

	  subsystem.vm.network "public_network", bridge: "#$DEF_IF", ip: "192.168.1.#{i+100}", auto_correct: true

	  subsystem.vm.provision "shell", inline: "echo -e $1 > /etc/nginx/conf.d/nginx.conf", args: "#{$reverseProxy} proxy_pass http://node_#{i};}}"
	  subsystem.vm.provision "shell", inline: "#{$bootScript}"

	  subsystem.vm.provision "chef_zero" do |chef|
	  	chef.log_level = "warn"
	    chef.install = false

	    chef.cookbooks_path = "../cookbooks"
	    chef.data_bags_path = "../data-bags"
	    chef.roles_path = "../roles"
	    chef.environments_path = "../environments"
	    chef.nodes_path = "../nodes"

	    chef.environment = "dev"
	    chef.add_role "api"
	    chef.add_role "web"

	    chef.run_list = VAGRANT_JSON["packages"]["nodes_0"]["run_list"]
	    chef.json = VAGRANT_JSON
	  end

	  subsystem.vm.provision "shell", inline: $userScript, privileged: false
	  subsystem.vm.provision "postchef", after: "chef", type: "shell", inline:<<-SHELL
	    echo 'chef installations completed.'
	  SHELL

    end
  end

  config.trigger.before :up do |t|
    t.info = "Bringing up your Vagrant guest machine!"
    t.run = {inline: "bash -c 'echo \"hey there!!\" > file.txt'"}
  end


end
